version: '3.7'

services:
  my-backend:
    image: asia.gcr.io/solid-feat-349705/team-project:1.16
    platform: linux/x86_64
    build:
      context: .
      dockerfile: Dockerfile
    # volumes:
    #   - ./src/:/myfolder/src/
    # env_file:
    #   - ./.env.prod
    ports:
      - 3000:3000

  # my-database:
  #   platform: linux/x86_64
  #   image: mysql:latest
  #   environment:
  #     MYSQL_DATABASE: 'mydocker02'
  #     MYSQL_ROOT_PASSWORD: 'root'
  #   ports:
  #     - 3306:3306
